# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /app/server
          - -f
          - /app/conf/conf.yaml
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: http
        - containerPort: {{ .Values.metricsPort }}
          name: metrics
        env:
        {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
        {{- end }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: app-conf
          mountPath: /app/conf
      volumes:
        - name: app-conf
          configMap:
            name: {{ .Values.appName }}-config
        - name: logs
          emptyDir: {}