version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.30.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "weaviate"
      ASYNC_INDEXING: "true"
      AUTHENTICATION_APIKEY_ENABLED: "false"
    volumes:
      - ./weaviate/data:/var/lib/weaviate