# 部署配置文件
# 将 out/ 目录下的 chart 文件与 values/ 目录下的配置文件对应
global:
  # 全局namespace,每个服务可以自定义.
  namespace: costrict
  # set 可以用于全局helm Set
  set: ""

data-services:
  # postgresql:
  #   values: postgresql-values.yaml
  #   chart: postgresql-16.6.6.tgz
  #   # storageClass，由于比较重要，直接从set中提出来，单独作为配置项
  #   # 由于不同helm包的key不一致或者会配置多个sc，此处通过key:value来配置。
  #   storageClass:
  #     "global.storageClass": "nfs-storage"
  # 采用高可用版本
  postgresql-ha:
    values: postgresql-ha-values.yaml
    chart: postgresql-ha-16.3.2.tgz
    storageClass:
      "global.defaultStorageClass": "nfs-storage"
  redis:
    values: redis-values.yaml
    chart: redis-20.3.0.tgz
    storageClass:
      "global.storageClass": "nfs-storage"
    
  weaviate:
    chart: weaviate-17.4.5.tgz
    values: weaviate-values.yaml
    storageClass:
      "storage.storageClassName": "nfs-storage"
    

tunnel:
  tunnel-manager:
    chart: tunnel-manager-0.1.0.tgz
    values: tunnel-manager-values.yaml
    storageClass:
      "persistence.storageClassName": "nfs-storage"
  cotun:
    # 可以移动到其他命名空间,需要修改调用方配置文件. values/codebase-server/querier-values.yaml
    namespace: costrict-cotun
    chart: cotun-0.1.0.tgz
    values: cotun-values.yaml

ai-gateway:
  higress:
    values: higress-values.yaml
    chart: higress-2.1.6.tgz
    storageClass:
      "higress-console.o11y.prometheus.pvc.storageClassName": "nfs-storage"
      "higress-console.o11y.grafana.pvc.storageClassName": "nfs-storage"
      "higress-console.o11y.loki.pvc.storageClassName": "nfs-storage"

  quota-manager:
    chart: quota-manager-0.1.0.tgz
    values: quota-manager-values.yaml
   
  quota-manager-frontend:
    chart: quota-manager-frontend-0.1.0.tgz
    values: quota-manager-frontend-values.yaml
    

auth:
  apisix:
    chart: apisix-2.11.2.tgz
    values: apisix-values.yaml
    storageClass:
      "etcd.persistence.storageClass": "nfs-storage"
  casdoor:
    chart: casdoor-helm-charts-v1.947.0.tgz
    values: casdoor-values.yaml
  oidc-auth:
    chart: oidc-auth-1.0.0.tgz
    values: oidc-values.yaml
  

chat-rag:
  chat-rag:
    chart: chat-rag-0.1.0.tgz
    values: chat-rag-values.yaml
    storageClass:
      "persistence.storageClassName": "nfs-storage"


code-completions:
  code-completions:
    chart: code-completions-0.1.0.tgz
    values: code-completions-values.yaml

    
code-review:
  code-review:
    chart: code-review-0.1.0.tgz
    values: code-review-values.yaml

      

codebase-server:
  codebase-embedder:
    chart: codebase-embedder-0.1.0.tgz
    values: embedder-values.yaml

  codebase-querier:
    chart: codebase-querier-0.1.0.tgz
    values: querier-values.yaml



frontend:
  credit-manager:
    chart: credit-manager-1.0.0.tgz
    values: credit-manager-values.yaml

portal:
  portal:
    chart: portal-0.1.0.tgz
    values: portal-values.yaml
    storageClass:
      "persistence.storageClassName": "nfs-storage"
  costrict-ssh-manager:
    chart: costrict-ssh-manager-0.1.0.tgz
    values: costrict-ssh-manager-values.yaml


statistics:
  pushgateway:
    chart: pushgateway-0.1.0.tgz
    values: pushgateway-values.yaml
    storageClass:
      "persistence.storageClassName": "nfs-storage"