# 副本数
replicaCount: 1

# 镜像配置
image:
  repository: "zgsm/quota-manager-frontend"
  pullPolicy: IfNotPresent
  tag: "1.0.8"

# 环境变量配置
env:
  TZ: Asia/Shanghai
  NODE_ENV: production
  VITE_API_BASE_URL: "http://10.200.101.5:31281"

# 资源限制
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP