apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - name: portal-web-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: portal-web-pvc
          mountPath: /var/www
      volumes:
      - name: portal-web-config
        configMap:
          name: {{ include "portal.fullname" . }}-config
      - name: portal-web-pvc
        persistentVolumeClaim:
          claimName: {{ include "portal.fullname" . }}-pvc