# values.yaml

# 应用配置
appName: code-completion
containerName: code-completion

# 副本数
replicaCount: 1

# 镜像配置
image:
  repository: "docker.io/zgsm/code-completion"
  pullPolicy: IfNotPresent
  tag: "v1.7.46"

# 资源限制
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "2Gi"
    cpu: "2"

# 配置文件参数
config:
  config.yaml: |
    codebaseContext:
      disableDefinitionSearch: true
      disableRelationSearch: true
      disableSemanticSearch: true
      codebaseDefinitionURL: "http://codebase-querier-svc:8888/codebase-indexer/api/v1/search/definition"
      codebaseSemanticURL: "http://codebase-querier-svc:8888/codebase-embedder/api/v1/search/semantic"
      codebaseRelationURL: "http://codebase-querier-svc:8888/codebase-indexer/api/v1/search/relation"
      semanticTopK: 5
      semanticScoreThreshold: 0.5
      relationLayer: 3
      relationIncludeContent: false
      requestTimeout: 1000ms
      totalTimeout: 2000ms
    models:
      - completionsUrl: "http://10.20.19.2:32081/v1/completions"
        modelName: "DeepSeek-Coder-V2-Lite-Base"
        authorization: ""
        timeout: 3000ms
        maxPrefixContext: 4096
        maxSuffixContext: 1024
        maxOutputToken: 50
        fimPrefix: "<｜fim▁begin｜>"
        fimMiddle: "<｜fim▁end｜>"
        fimSuffix: "<｜fim▁hole｜>"
        fimStop: ["<｜end▁of▁sentence｜>", "<|EOT|>", "▁<MID>"]
        tokenizerPath: "bin/cgtok/starcoder_tokenizer.json"
        maxConcurrent: 30
    streamController:
      maintainInterval: 300s
      completionTimeout: 4500ms
    completionsConfig:
      disableScore: true
      disableLanguageFeature: false
      thresholdScore: 0.3
      strPattern: ".*"
      treePattern: ".*"
      lineCountThreshold: 100
      endTag: "</completion>"

# Service 配置
service:
  name: code-completion
  type: ClusterIP
  port: 8080
  targetPort: 8080

# ServiceMonitor 配置
serviceMonitor:
  enabled: true
  name: code-completion-costrict
  namespace: monitoring
  path: /metrics
  interval: 15s
  labels: {}
  # 可选的 metricRelabelings 配置
  metricRelabelings: []
  # 可选的 relabelings 配置
  relabelings: []

# 资源限制
resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

# HPA 配置
hpa:
 enabled: true # 是否启用 HPA
 minReplicas: 1 # 最小副本数
 maxReplicas: 9 # 最大副本数
 targetCPUUtilizationPercentage: 95 # CPU 使用率目标百分比
 targetMemoryUtilizationPercentage: 85 # 内存使用率目标百分比
 behavior:
   scaleUp:
     stabilizationWindowSeconds: 30 # 扩容稳定窗口时间
     policies:
     - type: Percent
       value: 50 # 每次最多增加 50% 的副本数
       periodSeconds: 60
     - type: Pods
       value: 2 # 每次最多增加 2 个副本
       periodSeconds: 60
     selectPolicy: Max # 选择较大的策略
   scaleDown:
     stabilizationWindowSeconds: 300 # 缩容稳定窗口时间（5分钟）
     policies:
     - type: Percent
       value: 10 # 每次最多减少 10% 的副本数
       periodSeconds: 60
     - type: Pods
       value: 1 # 每次最多减少 1 个副本
       periodSeconds: 60
     selectPolicy: Min # 选择较小的策略

# ServiceMonitor 配置
serviceMonitor:
  enabled: true