useDaemonSet: true
apisix:
  ssl:
    enabled: false
    # fallbackSNI: "costrict.sangfor.com"
  admin:
    allow:
      ipList:
      - 0.0.0.0/0
    credentials:
      secretName: ""
      admin: "costrict-2025-admin" # admin key
      viewer: "costrict-2025"
    type: ClusterIP
  enabled: true
  nginx:
    logs:
      errorLogLevel: "warn"
      # 给日志加上requestId打印
      accessLogFormat: '$remote_addr - $remote_user [$time_local] $http_host \"$request\" $status $body_bytes_sent [rid:$http_x_request_id] $request_time \"$http_referer\" \"$http_user_agent\" $upstream_addr $upstream_status $upstream_response_time \"$upstream_scheme://$upstream_host$upstream_uri\"'
    configurationSnippet:
      httpSrv: |
        proxy_ignore_client_abort       off;
        proxy_connect_timeout 10s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 @error_$extension;

        location @error_json {
          types { } default_type "application/json; charset=utf-8";
          echo '{"message": "$status_text"}';
        }
      httpStart: |
        more_clear_headers Serve;
        client_body_buffer_size 2m;

        map $status $status_text {
          400 'Bad Request';
          401 'Unauthorized';
          402 'Payment Required';
          403 'Forbidden';
          404 'Not Found';
          405 'Method Not Allowed';
          406 'Not Acceptable';
          407 'Proxy Authentication Required';
          408 'Request Timeout';
          409 'Conflict';
          410 'Gone';
          411 'Length Required';
          412 'Precondition Failed';
          413 'Payload Too Large';
          414 'URI Too Long';
          415 'Unsupported Media Type';
          416 'Range Not Satisfiable';
          417 'Expectation Failed';
          418 'I\'m a teapot';
          421 'Misdirected Request';
          422 'Unprocessable Entity';
          423 'Locked';
          424 'Failed Dependency';
          425 'Too Early';
          426 'Upgrade Required';
          428 'Precondition Required';
          429 'Too Many Requests';
          431 'Request Header Fields Too Large';
          451 'Unavailable For Legal Reasons';
          500 'Internal Server Error';
          501 'Not Implemented';
          502 'Bad Gateway';
          503 'Service Unavailable';
          504 'Gateway Timeout';
          505 'HTTP Version Not Supported';
          506 'Variant Also Negotiates';
          507 'Insufficient Storage';
          508 'Loop Detected';
          510 'Not Extended';
          511 'Network Authentication Required';
          default 'Something is wrong';
        }
        map $http_accept $extension {
          default json;
          ~*application/json json;
        }
      httpEnd: |
        proxy_buffer_size 128k;
        proxy_buffers 64 128k;
        proxy_busy_buffers_size 256k;
      
    workerProcesses: 8
  prometheus:
    enabled: true
  ssl:
    enabled: true
dashboard:
  config:
    authentication:
      users:
      - password: costrict
        username: admin
    conf:
      allow_list:
      - 0.0.0.0/0
  enabled: true
  service:
    type: ClusterIP
etcd:
  enabled: true
  persistence:
    enabled: true
    storageClass: costrict-nfs
    accessModes:
    - ReadWriteMany
image:
  tag: 3.9.1-debian
metrics:
  serviceMonitor:
    enabled: false
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 100Mi
service:
  http:
    enabled: true
  tls:
    nodePort: 30444
