global:
  storageClass: "costrict-nfs"

image:
  registry: "docker.io"
  repository: "bitnami/postgresql"
  tag: "17.5.0-debian-12-r20"

auth:
  password: "costrict"
  username: "costrict"
  database: "costrict"
  # 显式设置复制用户和密码（非常重要！）
  replicationUser: "repluser"
  replicationPassword: "replpass"

# ✅ 关键：启用复制架构
architecture: replication

audit:
  logTimezone: "Asia/Shanghai"

primary:
  initdb:
    scripts:
      init_user_db.sql: |
        CREATE USER costrict WITH PASSWORD 'costrict';
        CREATE DATABASE codebase_embedder ENCODING 'UTF8';
        CREATE DATABASE casdoor ENCODING 'UTF8';
        CREATE DATABASE codereview ENCODING 'UTF8';
        CREATE DATABASE auth ENCODING 'UTF8';
        CREATE DATABASE quota_manager ENCODING 'UTF8';

  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
    - name: POSTGRESQL_MAX_CONNECTIONS
      value: "1000"

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 5

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi

  service:
    type: ClusterIP  # 建议主库不暴露 NodePort

  persistence:
    enabled: true
    size: 200Gi
    accessModes:
      - ReadWriteMany

# ✅ 配置只读副本
readReplicas:
  replicaCount: 2

  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 5

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi

  service:
    type: ClusterIP  # 可根据需要改为 LoadBalancer 或保留 ClusterIP

  persistence:
    enabled: true
    size: 200Gi  # ✅ 与主节点一致
    accessModes:
      - ReadWriteMany

backup:
  enabled: true
  cronjob:
    timeZone: Asia/Shanghai
    schedule: "0 0 * * *"
    successfulJobsHistoryLimit: 1
    storage:
      enabled: true
      size: 50Gi
      accessModes:
        - ReadWriteMany

volumePermissions:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: false