# weaviate-values.yaml
# ===================================
# 镜像配置
# ===================================
image:
  registry: "docker.io"
  repo: semitechnologies/weaviate
  tag: 1.30.0
  pullPolicy: IfNotPresent

# ===================================
# 存储配置 (PVC)
# ===================================
storage:
  size: 100Gi
  # ✅ 正确字段：storageClassName
  storageClassName: "costrict-nfs"
  # accessModes 由 StatefulSet 自动生成，默认为 ReadWriteOnce
  # 如果需要 ReadWriteMany，需通过 volumeClaimTemplates 覆盖（见下方）

# ===================================
# Weaviate 运行时配置 (通过环境变量)
# ===================================
# 所有 Weaviate 配置都通过 env 字段设置
env:
  # 数据存储路径
  PERSISTENCE_DATA_PATH: /var/lib/weaviate
  # 查询默认 limit
  QUERY_DEFAULTS_LIMIT: -25
  # 匿名访问
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
  ASYNC_INDEXING: true
  DEFAULT_VECTORIZER_MODULE: "none"
  AUTHENTICATION_APIKEY_ENABLED: "false"

# ===================================
# 资源限制
# ===================================
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# ===================================
# 服务配置 (Service)
# ===================================
service:
  name: weaviate
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP

# ===================================
# 副本数（StatefulSet）
# ===================================
replicas: 1

# ===================================
# Init Containers
# ===================================
initContainers:
  sysctlInitContainer:
    enabled: false
  ensureFileOwnershipContainer:
    enabled: false


# ===================================
# 健康检查（可选调整）
# ===================================
readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  initialDelaySeconds: 900
  periodSeconds: 10
  failureThreshold: 30


# ===================================
# 指标监控
# ===================================
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
