# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
data:
  conf.yaml: |-
{{ index .Values.config "conf.yaml" | indent 4 }}